project:
  type: book
  output-dir: docs
  resources: 
    - TUS26_04.qmd
    - TUS26_11.qmd
    - UKDS_TUS_Mullan.qmd
  render:
    - "*.qmd"
    - "TUS26_04.qmd"

execute:
  warning: false
  message: false
  freeze: false
  
book:
  title: Introduction to  time diary data
#  subtitle: Day 1 exercices
  author: UK Data Service and Centre for Time Use Research
#  organisation:   UK Data Service  
  downloads: [pdf]
#  output-file: "BSA_Exercices"
  date: "June 2026"
  date-format: MMMM YYYY
  chapters:
    - index.qmd
    - part: "Day 1 practicals"
      chapters:
#        text: "Test day 1"
        - workbook_04.qmd
        
    - part: "Day 2 Practicals"
      chapters:
        - workbook_11.qmd

  sidebar:
    style: "floating"
    search: true
    title: " "
    logo: pics/UKDS_Logos_Col_Grey_300dpi.png
    logo-href: https://ukdataservice.ac.uk/
    logo-alt: "UK Data Service Logo and link to website"


#bibliography: references.bib
jupyter: nbstata
pdf-engine: lualatex

format:
    html: 
      code-overflow: scroll
      code-line-numbers: true
      page-layout: full
      toc: true
      toc-location: right
      highlight-style: arrow-light
      smooth-scroll: true
      link-external-newwindow: true
      citations-hover: true
      footnotes-hover: true
      css: ukds_long.css
      number-sections: false


    # docx: 
    #  fig-width: 7
    #  papersize: A4

    # titlepage-pdf:
    #  titlepage: plain
    #  titlepage-geometry:
    #   - top=70mm
    #   - left=30mm
    #   - right=30mm
    #   - bottom=30mm
    #  titlepage-theme:
    #   logo-size: 3cm
    #   title-fontstyle: Huge
    #  titlepage-logo: "pics/UKDS_Logos_Col_Grey_300dpi.png"  
    #  documentclass: scrreport
    #  fig-width: 7
    #  papersize: A4
    #  include-in-header: preamble.tex
    #  geometry:
    #   - top=25mm
    #   - left=25mm
    #   - right=25mm
    #   - bottom=30mm
